FROM openknowledge/ckan-dev:2.9

MAINTAINER Your Name Here <you@example.com>

# Set timezone
ARG TZ
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime
RUN echo $TZ > /etc/timezone

# Install any extensions needed by your CKAN instance
# (Make sure to add the plugins to CKAN__PLUGINS in the .env file)
# For instance:
RUN echo "installing plugins" && \
    # paste
    pip install -e git+https://github.com/cdent/paste.git#egg=paste && \
    # scheming
    pip install -e git+https://github.com/ckan/ckanext-scheming.git#egg=ckanext-scheming && \
    # harvest
    pip install -e git+https://github.com/ckan/ckanext-harvest.git#egg=ckanext-harvest && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-harvest/master/requirements.txt &&  \
    #socrata harvester
    # pip install -e git+https://github.com/opendatamonitor/socrata-harvester.git#egg=socrata-harvest && \
    # pip install -r https://raw.githubusercontent.com/opendatamonitor/socrata-harvester/master/pip-requirements.txt
    #dcat harvester
    pip install -e git+https://github.com/ckan/ckanext-dcat.git#egg=ckanext-dcat && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-dcat/master/requirements.txt && \
    #googleanalytics
    pip install -e  git+https://github.com/ckan/ckanext-googleanalytics.git#egg=ckanext-googleanalytics && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-googleanalytics/master/requirements.txt && \
    # pip install -e git+https://github.com/ckan/ckanext-disqus.git#egg=disqus
    # hierarchy
    pip install -e git+https://github.com/davidread/ckanext-hierarchy.git#egg=ckanext-hierarchy && \
    # showcase
    pip install -e git+https://github.com/ckan/ckanext-showcase.git#egg=ckanext-showcase && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-showcase/master/requirements.txt && \
    # geoview
    pip install git+https://github.com/ckan/ckanext-geoview.git#egg=ckanext-geoview && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-geoview/master/dev-requirements.txt && \
    #pdfview
    pip install -e git+https://github.com/ckan/ckanext-pdfview.git#egg=ckanext-pdfview && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-pdfview/master/dev-requirements.txt && \
    # contact
    pip install -e git+https://github.com/NaturalHistoryMuseum/ckanext-contact.git#egg=ckanext-contact

# Install npm and postcss
RUN apk add --no-cache npm && \
    npm install postcss@"^6.0.11" \
    postcss-cli@"^5.0.1" \
    autoprefixer@"^7.2.5" \
    postcss-calc@"^6.0.1" \
    postcss-clean@"^1.1.0" \
    postcss-color-function@"^4.0.1" \
    postcss-custom-media@"^6.0.0" \
    postcss-custom-properties@"^6.2.0" \
    postcss-import@"^11.0.0" \
    postcss-mixins@"^6.2.0" \
    postcss-nesting@"^4.2.1"

# Clone the extension(s) your are writing for your own project in the `src` folder
# to get them mounted in this image at runtime

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)
# See https://github.com/okfn/docker-ckan#applying-patches
COPY patches ${APP_DIR}/patches
COPY docker-entrypoint.d /docker-entrypoint.d/

RUN for d in $APP_DIR/patches/*; do \
    if [ -d $d ]; then \
    for f in `ls $d/*.patch | sort -g`; do \
    cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
    done ; \
    fi ; \
    done
