name: Build and publish all docker-ckan Images
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set CKAN Versions
        run: |
          echo CKAN_v2_8=$(grep 'ENV GIT_BRANCH' ckan-base/2.8/Dockerfile | cut -d '-' -f 2) >> $GITHUB_ENV
          echo CKAN_v2_9=$(grep 'ENV GIT_BRANCH' ckan-base/2.9/Dockerfile | cut -d '-' -f 2) >> $GITHUB_ENV
      - name: Build ckan-base 2.8 and ${{ env.CKAN_v2_8 }}
        uses: docker/build-push-action@v2
        with:
          context: ckan-base
          file: ckan-base/2.8/Dockerfile
          push: true
          tags: |
            openknowledge/ckan-base:2.8
            openknowledge/ckan-base:${{ env.CKAN_v2_8 }}
      - name: Build ckan-base 2.9 and ${{ env.CKAN_v2_9 }}
        uses: docker/build-push-action@v2
        with:
          context: ckan-base
          file: ckan-base/2.9/Dockerfile
          push: true
          tags: |
            openknowledge/ckan-base:2.9
            openknowledge/ckan-base:${{ env.CKAN_v2_9 }}
      - name: Build ckan-base 2.9-py2 and ${{ env.CKAN_v2_8 }}-py2
        uses: docker/build-push-action@v2
        with:
          context: ckan-base
          file: ckan-base/2.9/Dockerfile.py2
          push: true
          tags: |
            openknowledge/ckan-base:2.9-py2
            openknowledge/ckan-base:${{ env.CKAN_v2_9 }}-py2
      - name: Build ckan-dev 2.8 and and ${{ env.CKAN_v2_8 }}
        uses: docker/build-push-action@v2
        with:
          context: ckan-dev
          file: ckan-dev/2.8/Dockerfile
          push: true
          tags: |
            openknowledge/ckan-dev:2.8
            openknowledge/ckan-dev:${{ env.CKAN_v2_8 }}
      - name: Build ckan-dev 2.9 and ${{ env.CKAN_v2_9 }}
        uses: docker/build-push-action@v2
        with:
          context: ckan-dev
          file: ckan-dev/2.9/Dockerfile
          push: true
          tags: |
            openknowledge/ckan-dev:2.9
            openknowledge/ckan-dev:${{ env.CKAN_v2_9 }}
      - name: Build ckan-dev 2.9-py2 and ${{ env.CKAN_v2_9 }}-py2
        uses: docker/build-push-action@v2
        with:
          context: ckan-dev
          file: ckan-dev/2.9/Dockerfile.py2
          push: true
          tags: |
            openknowledge/ckan-dev:2.9-py2
            openknowledge/ckan-dev:${{ env.CKAN_v2_9 }}-py2
